CREATE DATABASE DB_ALEXANDRA_RH;

USE DB_ALEXANDRA_RH;

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
DEPARTAMENTO CHAR(255),
FUNCAO CHAR(255),
IDADE INT,
SALARIO NUMERIC(8,2),
PRIMARY KEY (ID)

);
SELECT * FROM TB_FUNCIONARIOS;
INSERT INTO TB_FUNCIONARIOS(NOME,DEPARTAMENTO,FUNCAO,IDADE,SALARIO)
VALUES("MARIA","ADMINISTRATIVO","AUXILIAR",34,2000),
("REGINA","GERENCIA","GERENTE",45,5000);

SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO >= 2000;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO < 2000;
UPDATE TB_FUNCIONARIOS SET SALARIO = 1500 WHERE ID = 1;
